import { Hotel } from '../types/hotels';

export const HOTELS: Hotel[] = [
  {
    id: 7257,
    broker: 'coobrastur',
    name: 'Jurerê Beach Village',
    unique_id: '7257',
    image: 'https://www.coobmais.com.br/images/hotel/7257/01.jpg',
    city: {
      slug: 'florianópolis',
      name: 'Florianópolis',
    },
    country: {
      slug: 'brasil',
      name: 'Brasil',
    },
    state: 'SC',
    coordinates: {
      longitude: '-484896.0',
      latitude: '-274394.0',
    },
    street: 'Alameda César Nascimento, 646, Jurerê, Florianópolis, SC',
    complement: '',
    points: 15000,
    total_days: 3,
    extra: 448.8,
    is_preferential: false,
    available_to_book: true,
    absolute_url: '/brasil/sc/florianopolis/jurere-beach-village/',
    by_request: false,
    position: {
      lng: -484896,
      lat: -274394,
    },
  },
  {
    id: 4481,
    broker: 'coobrastur',
    name: 'Costão do Santinho Resort',
    unique_id: '4481',
    image: 'https://www.coobmais.com.br/images/hotel/4481/01.jpg',
    city: {
      slug: 'florianópolis',
      name: 'Florianópolis',
    },
    country: {
      slug: 'brasil',
      name: 'Brasil',
    },
    state: 'SC',
    coordinates: {
      longitude: '-483812.0',
      latitude: '-274647.0',
    },
    street:
      'Estrada Vereador Onildo Lemos, 2.505, Praia do Santinho, Florianópolis, SC',
    complement: '',
    points: 15000,
    total_days: 3,
    extra: 1849.26,
    is_preferential: false,
    available_to_book: true,
    absolute_url: '/brasil/sc/florianopolis/costao-do-santinho-resort/',
    by_request: true,
    position: {
      lng: -483812,
      lat: -274647,
    },
  },
  {
    id: 4038,
    broker: 'coobrastur',
    name: 'Das Nações Hotel',
    unique_id: '4038',
    image: 'https://www.coobmais.com.br/images/hotel/4038/01.jpg',
    city: {
      slug: 'florianópolis',
      name: 'Florianópolis',
    },
    country: {
      slug: 'brasil',
      name: 'Brasil',
    },
    state: 'SC',
    coordinates: {
      longitude: '-484583.0',
      latitude: '-274324.0',
    },
    street: 'Rua José da Rosa, 265, Canasvieiras, Florianópolis, SC',
    complement: '',
    points: 15000,
    total_days: 3,
    extra: 0,
    is_preferential: true,
    available_to_book: true,
    absolute_url: '/brasil/sc/florianopolis/das-nacoes-hotel/',
    by_request: false,
    position: {
      lng: -484583,
      lat: -274324,
    },
  },
  {
    id: 3678,
    broker: 'coobrastur',
    name: 'Mercure Florianópolis',
    unique_id: '3678',
    image: 'https://www.coobmais.com.br/images/hotel/3678/01.jpg',
    city: {
      slug: 'florianópolis',
      name: 'Florianópolis',
    },
    country: {
      slug: 'brasil',
      name: 'Brasil',
    },
    state: 'SC',
    coordinates: {
      longitude: '-485099.0',
      latitude: '-27578.0',
    },
    street: 'Rodovia Admar Gonzaga, 600, Itacorubi, Florianópolis, SC',
    complement: '',
    points: 15000,
    total_days: 3,
    extra: 0,
    is_preferential: true,
    available_to_book: true,
    absolute_url: '/brasil/sc/florianopolis/mercure-florianopolis/',
    by_request: false,
    position: {
      lng: -485099,
      lat: -27578,
    },
  },
  {
    id: 6254,
    broker: 'coobrastur',
    name: 'Intercity Florianópolis',
    unique_id: '6254',
    image: 'https://www.coobmais.com.br/images/hotel/6254/01.jpg',
    city: {
      slug: 'florianópolis',
      name: 'Florianópolis',
    },
    country: {
      slug: 'brasil',
      name: 'Brasil',
    },
    state: 'SC',
    coordinates: {
      longitude: '-485589.0',
      latitude: '-275954.0',
    },
    street: 'Av. Paulo Fontes, 1.210, Centro, Florianópolis, SC',
    complement: '',
    points: 15000,
    total_days: 3,
    extra: 0,
    is_preferential: true,
    available_to_book: true,
    absolute_url: '/brasil/sc/florianopolis/intercity-florianopolis/',
    by_request: false,
    position: {
      lng: -485589,
      lat: -275954,
    },
  },
  {
    id: 6964,
    broker: 'coobrastur',
    name: 'Intercity Portofino Florianópolis',
    unique_id: '6964',
    image: 'https://www.coobmais.com.br/images/hotel/6964/01.jpg',
    city: {
      slug: 'florianópolis',
      name: 'Florianópolis',
    },
    country: {
      slug: 'brasil',
      name: 'Brasil',
    },
    state: 'SC',
    coordinates: {
      longitude: '-485009.0',
      latitude: '-275517.0',
    },
    street: 'Rodovia José Carlos Daux, 3270, Saco Grande, Florianópolis, SC',
    complement: '',
    points: 15000,
    total_days: 3,
    extra: 0,
    is_preferential: true,
    available_to_book: true,
    absolute_url: '/brasil/sc/florianopolis/intercity-portofino-florianopolis/',
    by_request: false,
    position: {
      lng: -485009,
      lat: -275517,
    },
  },
  {
    id: 3644,
    broker: 'coobrastur',
    name: 'Oceania Park Hotel',
    unique_id: '3644',
    image: 'https://www.coobmais.com.br/images/hotel/3644/01.jpg',
    city: {
      slug: 'florianópolis',
      name: 'Florianópolis',
    },
    country: {
      slug: 'brasil',
      name: 'Brasil',
    },
    state: 'SC',
    coordinates: {
      longitude: '-484026.0',
      latitude: '-27433.0',
    },
    street: 'Rua do Marisco, 560, Ingleses do Rio Vermelho, Florianópolis, SC',
    complement: '',
    points: 15000,
    total_days: 3,
    extra: 0,
    is_preferential: true,
    available_to_book: true,
    absolute_url: '/brasil/sc/florianopolis/oceania-park-hotel/',
    by_request: false,
    position: {
      lng: -484026,
      lat: -27433,
    },
  },
  {
    id: 405,
    broker: 'coobrastur',
    name: 'São Sebastião da Praia Hotel',
    unique_id: '405',
    image: 'https://www.coobmais.com.br/images/hotel/405/01.jpg',
    city: {
      slug: 'florianópolis',
      name: 'Florianópolis',
    },
    country: {
      slug: 'brasil',
      name: 'Brasil',
    },
    state: 'SC',
    coordinates: {
      longitude: '-484855.0',
      latitude: '-276761.0',
    },
    street: 'Av. Campeche, 1373, Praia do Campeche, Florianópolis, SC',
    complement: '',
    points: 15000,
    total_days: 3,
    extra: 0,
    is_preferential: true,
    available_to_book: true,
    absolute_url: '/brasil/sc/florianopolis/sao-sebastiao-da-praia-hotel/',
    by_request: false,
    position: {
      lng: -484855,
      lat: -276761,
    },
  },
  {
    id: 4872,
    broker: 'coobrastur',
    name: 'Slaviero Baía Norte Florianópolis',
    unique_id: '4872',
    image: 'https://www.coobmais.com.br/images/hotel/4872/01.jpg',
    city: {
      slug: 'florianópolis',
      name: 'Florianópolis',
    },
    country: {
      slug: 'brasil',
      name: 'Brasil',
    },
    state: 'SC',
    coordinates: {
      longitude: '-485626.0',
      latitude: '-275909.0',
    },
    street: 'Av. Beira Mar Norte, 220, Centro, Florianópolis, SC',
    complement: '',
    points: 15000,
    total_days: 3,
    extra: 0,
    is_preferential: true,
    available_to_book: true,
    absolute_url: '/brasil/sc/florianopolis/slaviero-baia-norte-florianopolis/',
    by_request: false,
    position: {
      lng: -485626,
      lat: -275909,
    },
  },
  {
    id: 7256,
    broker: 'coobrastur',
    name: 'Balmare Hotel',
    unique_id: '7256',
    image: 'https://www.coobmais.com.br/images/hotel/7256/01.jpg',
    city: {
      slug: 'florianópolis',
      name: 'Florianópolis',
    },
    country: {
      slug: 'brasil',
      name: 'Brasil',
    },
    state: 'SC',
    coordinates: {
      longitude: '-484326.0',
      latitude: '-274217.0',
    },
    street: 'Rua Leonel Pereira, 78, Cachoeira do Bom Jesus, Florianópolis, SC',
    complement: '',
    points: 15000,
    total_days: 3,
    extra: 0,
    is_preferential: true,
    available_to_book: true,
    absolute_url: '/brasil/sc/florianopolis/balmare-hotel/',
    by_request: true,
    position: {
      lng: -484326,
      lat: -274217,
    },
  },
  {
    id: 6572,
    broker: 'coobrastur',
    name: 'Porto Madero Hotel',
    unique_id: '6572',
    image: 'https://www.coobmais.com.br/images/hotel/6572/01.jpg',
    city: {
      slug: 'florianópolis',
      name: 'Florianópolis',
    },
    country: {
      slug: 'brasil',
      name: 'Brasil',
    },
    state: 'SC',
    coordinates: {
      longitude: '-484564.0',
      latitude: '-274297.0',
    },
    street: 'Rua Manoel Mancellos Moura, 488, Canasvieiras, Florianópolis, SC',
    complement: '',
    points: 15000,
    total_days: 3,
    extra: 0,
    is_preferential: true,
    available_to_book: true,
    absolute_url: '/brasil/sc/florianopolis/porto-madero-hotel/',
    by_request: false,
    position: {
      lng: -484564,
      lat: -274297,
    },
  },
  {
    id: 3608,
    broker: 'coobrastur',
    name: 'Praia Brava Hotel',
    unique_id: '3608',
    image: 'https://www.coobmais.com.br/images/hotel/3608/01.jpg',
    city: {
      slug: 'florianópolis',
      name: 'Florianópolis',
    },
    country: {
      slug: 'brasil',
      name: 'Brasil',
    },
    state: 'SC',
    coordinates: {
      longitude: '-484154.0',
      latitude: '-274.0',
    },
    street:
      'Rua Professor Ari Kardec Bosco de Melo, 147, Praia Brava, Florianópolis, SC',
    complement: '',
    points: 15000,
    total_days: 3,
    extra: 0,
    is_preferential: true,
    available_to_book: true,
    absolute_url: '/brasil/sc/florianopolis/praia-brava-hotel/',
    by_request: false,
    position: {
      lng: -484154,
      lat: -274,
    },
  },
  {
    id: 4330,
    broker: 'coobrastur',
    name: 'Marinas Palace Hotel',
    unique_id: '4330',
    image: 'https://www.coobmais.com.br/images/hotel/4330/01.jpg',
    city: {
      slug: 'florianópolis',
      name: 'Florianópolis',
    },
    country: {
      slug: 'brasil',
      name: 'Brasil',
    },
    state: 'SC',
    coordinates: {
      longitude: '-484565.0',
      latitude: '-274284.0',
    },
    street: 'Rua Manoel Mancellos Moura, 630, Canasvieiras, Florianópolis, SC',
    complement: '',
    points: 15000,
    total_days: 3,
    extra: 0,
    is_preferential: true,
    available_to_book: true,
    absolute_url: '/brasil/sc/florianopolis/marinas-palace-hotel/',
    by_request: false,
    position: {
      lng: -484565,
      lat: -274284,
    },
  },
  {
    id: 4174,
    broker: 'coobrastur',
    name: 'Cambirela Hotel',
    unique_id: '4174',
    image: 'https://www.coobmais.com.br/images/hotel/4174/01.jpg',
    city: {
      slug: 'florianópolis',
      name: 'Florianópolis',
    },
    country: {
      slug: 'brasil',
      name: 'Brasil',
    },
    state: 'SC',
    coordinates: {
      longitude: '-485866.0',
      latitude: '-275813.0',
    },
    street: 'Av. Marinheiro Max Schramm, 2199, Estreito, Florianópolis, SC',
    complement: '',
    points: 15000,
    total_days: 3,
    extra: 46.2,
    is_preferential: false,
    available_to_book: true,
    absolute_url: '/brasil/sc/florianopolis/cambirela-hotel/',
    by_request: false,
    position: {
      lng: -485866,
      lat: -275813,
    },
  },
  {
    id: 4314,
    broker: 'coobrastur',
    name: 'Canto da Ilha Hotel',
    unique_id: '4314',
    image: 'https://www.coobmais.com.br/images/hotel/4314/01.jpg',
    city: {
      slug: 'florianópolis',
      name: 'Florianópolis',
    },
    country: {
      slug: 'brasil',
      name: 'Brasil',
    },
    state: 'SC',
    coordinates: {
      longitude: '-484234.0',
      latitude: '-274079.0',
    },
    street:
      'Av. Luiz Boiteux Piazza, 4.810, Ponta das Canas, Florianópolis, SC',
    complement: '',
    points: 15000,
    total_days: 3,
    extra: 0,
    is_preferential: true,
    available_to_book: true,
    absolute_url: '/brasil/sc/florianopolis/canto-da-ilha-hotel/',
    by_request: false,
    position: {
      lng: -484234,
      lat: -274079,
    },
  },
  {
    id: 105,
    broker: 'coobrastur',
    name: 'Castelmar Hotel',
    unique_id: '105',
    image: 'https://www.coobmais.com.br/images/hotel/105/01.jpg',
    city: {
      slug: 'florianópolis',
      name: 'Florianópolis',
    },
    country: {
      slug: 'brasil',
      name: 'Brasil',
    },
    state: 'SC',
    coordinates: {
      longitude: '-485607.0',
      latitude: '-275909.0',
    },
    street: 'Rua Felipe Schmidt, 1.260, Centro, Florianópolis, SC',
    complement: '',
    points: 15000,
    total_days: 3,
    extra: 0,
    is_preferential: true,
    available_to_book: true,
    absolute_url: '/brasil/sc/florianopolis/castelmar-hotel/',
    by_request: false,
    position: {
      lng: -485607,
      lat: -275909,
    },
  },
];
